#pragma once
#include "complex/qcu_complex.cuh"
#include <type_traits>
#include "qcu_blas/qcu_blas_complex_axpby.h"
#include "qcu_blas/qcu_blas_complex_axpbypcz.h"
#include "qcu_blas/qcu_blas_complex_dotc.h"
#include "qcu_blas/qcu_blas_complex_norm.h"
#include "qcu_blas/qcu_blas_complex_xpay.h"
#include "qcu_blas/qcu_blas_complex_xsay.h"
#include "qcu_blas/qcu_blas_elementwise_div.h"